language: python

python:
 - 3.6 

services: 
 - docker 

sudo: required

# env:
#   - CODECOV_TOKEN='4de5b3c5-f2c9-4806-8c06-fbf401288c48'

before_install:
  - pip3 install docker-compose
  - chmod +x api/tests.sh

jobs:
  include:
    - stage: build
      script:
      - docker-compose up -d --build 
    - stage: test
      script:
      - docker-compose run client yarn quasar test --unit jest
      - docker-compose run --rm api sh -c "python manage.py test"


# after_success:
#   - bash <(curl -s https://codecov.io/bash)