version: "3.3"
services: 
    db: 
        image: postgres:13
        container_name: postgres-container
        restart: always
        env_file:
            - db.env
        ports:
            - "5432:5432"

    api:
        build: ./api/
        container_name: api-container
        restart: always
        volumes: 
            - ./api:/api
        ports:
            - "8000:8000"
        env_file:
            - db.env
        depends_on: 
            - db

    client:
        build: ./client/
        container_name: client-container
        restart: always
        volumes: 
            - ./client:/client
        ports: 
            - "8080:8080"
