# This is a basic workflow to help you get started with Actions

name: API CI

on: [push, pull_request]

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
        uses: actions/checkout@v2
      - name: Verificação de Dependencias de cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Criando ambiente do python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
        run: python --version
        working-directory: api
      - name: Instalando requirements.txt
        run: pip install -r requirements.txt
        working-directory: api
      - name: Rodando Migrações
        run: python manage.py migrate
        working-directory: api
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
      - name: Rodando testes do ambiente
        run: python manage.py test
        working-directory: api
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
